### ISSUE TITLE
Update package at packagist.org

### ISSUE THREAD

**Issue by SeyamMs** [afatmustafa/blade-hugeicons#2]
support for laravel 10 was added to the repo but not to packagist.
I was able to install this package after adding this repo to my composer.json file like so:

`
 "repositories": [
        {
            "type": "git",
            "url": "https://github.com/afatmustafa/blade-hugeicons.git"
        }
    ],
`

then requiring it with dev-main version to instruct composer to look in the previous repo as the package is already exists on packagist.

`composer require afatmustafa/blade-hugeicons:dev-main`

please update the package at packagist.org to be able to install it directly with composer.

**Comment by afatmustafa** [comment]
Hi, I have released version 0.0.3. It can now be installed in Laravel 10 without requiring the dev-main branch.

**Comment by SeyamMs** [comment]
Thank you, this is the fastest response I've experienced 💯 
updating my composer again

**Comment by afatmustafa** [comment]
It completely slipped my mind 😄, thank you for reminding me. Happy coding.
