### ISSUE TITLE
Package out of sync with icons

### ISSUE THREAD

**Issue by lewislarsen** [afatmustafa/blade-hugeicons#4]
Hi there, 

The package looks to be out-of-date with the current offerings available on hugeicons. Lots of icons, i.e. https://hugeicons.com/icon/pulse-02-stroke-rounded aren't available with your composer package.

Are there any plans to update? 

Thank you!

**Comment by afatmustafa** [comment]
Hi, yes I have sadly realized this myself recently 😄, the update will come as soon as possible.

**Comment by lewislarsen** [comment]
> Hi, yes I have sadly realized this myself recently 😄, the update will come as soon as possible.

Awesome news - thanks a bunch!

**Comment by afatmustafa** [comment]
You're welcome, i am closing closing this issue right now, stay tuned for the next update 🙌

**Comment by afatmustafa** [comment]
Hey Lewis! I just released v0.0.4 with 222 new icons (Crazy, right?). Just wanted to let you know since you asked about new icons.

**Comment by lewislarsen** [comment]
> Hey Lewis! I just released v0.0.4 with 222 new icons (Crazy, right?). Just wanted to let you know since you asked about new icons.

Awesome, thank you for being quick on this. Much appreciated. :)
